#!/usr/bin/env escript
%% emit_erlang.escript <arc_dir> <in.cjs> <module_name> <out.erl>
main([ArcDir, In, ModName, Out]) ->
    Ebins = filelib:wildcard(filename:join([ArcDir, "aot", "build", "dev", "erlang", "*", "ebin"])),
    Ebins =/= [] orelse fail("no ebin dirs under ~s/aot/build. Run `gleam build` in ~s/aot first", [ArcDir, ArcDir]),
    ok = code:add_pathsa(Ebins),
    {ok, Src} = file:read_file(In),
    Name = unicode:characters_to_binary(ModName),
    T0 = erlang:monotonic_time(millisecond),
    Ir = case 'arc_aot@compile':to_ir(Src, Name) of
             {ok, I} -> I;
             {error, E1} -> fail("compile: ~s", ['arc_aot@compile':describe(E1)])
         end,
    CMod = case 'carder@pipeline':ir_to_cmod(Ir, 'arc_aot@emit':binding()) of
               {ok, C} -> C;
               {error, E2} -> fail("pipeline: ~s", ['carder@pipeline':describe(E2)])
           end,
    Forms = case 'carder@backend@eaf':module_forms(CMod) of
                {ok, F} -> F;
                {error, E3} -> fail("forms: ~s", ['carder@backend@eaf':describe(E3)])
            end,
    Header = unicode:characters_to_binary(io_lib:format(
        "%% Generated by scripts/build.sh. react ~s, react-dom ~s, compiled by Arc.~n~n",
        [pkg_version("react"), pkg_version("react-dom")])),
    Erl0 = arc_aot_pp_ffi:forms_to_erl(Forms),
    %% thousands of unused vars, and erlc re-reads the 9 MB source per warning
    Erl = binary:replace(Erl0, <<"\n-export(">>,
                         <<"\n-compile([nowarn_unused_vars]).\n\n-export(">>),
    ok = file:write_file(Out, [Header, Erl]),
    io:format("wrote ~s (~p bytes) in ~pms~n", [Out, iolist_size([Header, Erl]), erlang:monotonic_time(millisecond) - T0]);
main(_) ->
    fail("usage: emit_erlang.escript <arc_dir> <in.cjs> <module_name> <out.erl>", []).

pkg_version(Pkg) ->
    Path = filename:join(["node_modules", Pkg, "package.json"]),
    case file:read_file(Path) of
        {ok, Json} ->
            case re:run(Json, <<"\"version\":\\s*\"([^\"]+)\"">>, [{capture, all_but_first, binary}]) of
                {match, [V]} -> V;
                nomatch -> <<"?">>
            end;
        {error, _} -> <<"?">>
    end.

fail(Fmt, Args) ->
    io:format(standard_error, Fmt ++ "~n", Args),
    halt(1).
